### ISSUE TITLE
Update the AfyaMoja USSD Projects read me

### ISSUE THREAD

**Issue by moshonk** [IntelliSOFT-Consulting/afyamoja-ussd-api#2]
In order to ensure continuity of support for this project, it is important to maintain some form of documentation that will help its future maintainers. As such we need to provide the following information on the projects readme file:

- [x] - Brief description
- [x] - Components (Already exists)
- [x] - Setting up the project
- [x] - Running the project
- [x] - Available API endpoints and what they do

**Comment by RodneyOnyi** [comment]
Hi Ken,

Noted, will take some time to do the documentation.

Kind Regards
Onyango Rodney.

**Comment by moshonk** [comment]
Thanks Rodney

Regards
Ken O.

**Comment by RodneyOnyi** [comment]
Hi Ken,

I have update the section on installation and running the application. 
Let me know if it is okay

**Comment by moshonk** [comment]
Looks good Rodney. Thanks.
